export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const REGISTER_SUCCEEDED = 'REGISTER_SUCCEEDED';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED';
export const GET_CURRENT_USER_START = 'GET_CURRENT_USER_START';
export const GET_CURRENT_USER_SUCCEEDED = 'GET_CURRENT_USER_SUCCEEDED';
export const GET_CURRENT_USER_FAILED = 'GET_CURRENT_USER_FAILED';

//#region Articles

export const GET_GLOBAL_ARTICLES_START = 'GET_GLOBAL_ARTICLES_START';
export const GET_GLOBAL_ARTICLES_SUCCEEDED = 'GET_GLOBAL_ARTICLES_SUCCEEDED';
export const GET_GLOBAL_ARTICLES_FAILED = 'GET_GLOBAL_ARTICLES_FAILED';
export const GET_ARTICLES_IN_FEED_START = 'GET_ARTICLES_IN_FEED_START';
export const GET_ARTICLES_IN_FEED_SUCCEEDED = 'GET_ARTICLES_IN_FEED_SUCCEEDED';
export const GET_ARTICLES_IN_FEED_FAILED = 'GET_ARTICLES_IN_FEED_FAILED';
export const UNLOAD_ARTICLES = 'UNLOAD_ARTICLES';

//#endregion Articles

//#region Tags

export const GET_TAGS_START = 'GET_TAGS_START';
export const GET_TAGS_SUCCEEDED = 'GET_TAGS_SUCCEEDED';
export const GET_TAGS_FAILED = 'GET_TAGS_FAILED';
export const UNLOAD_TAGS = 'UNLOAD_TAGS';

//#endregion Tags
